### ISSUE TITLE
BUG (Melhoria) Placeholder (Procure por ID)

### ISSUE THREAD

**Issue by Albertodc1981** [redspark-io/invoice-system-quality#14]
# BUG (Melhoria)

---

## 1. Tela Figma 

Print correspondente a tela do FIGMA para comparação com a tela desenvolvida logo abaixo.

![Image](https://github.com/redspark-io/invoice-system-quality/assets/140550968/fe7eacb1-caed-4d50-8a8f-4bf073ec4f0a)
 
---

## 2. Tela Localhost

Conforme print abaixo input está desproporcional comparado com a tela do FIGMA.
 

![Image](https://github.com/redspark-io/invoice-system-quality/assets/140550968/c1d3146f-b7ab-460b-b567-dfc28f97b075)

---

## 3. Margem ao digitar caracteres
Feito vídeo ,ao digitar caracteres no input ele não observa a margem.

Segue a evidência no link:https://jam.dev/c/2a5908d3-a4e3-460a-8fce-e015d5cb4268

Verificado no ambiente de FE em DEV

**Comment by bryansantosdeve** [comment]
Correção de bug aplicada na [Issue #25](https://github.com/redspark-io/invoice-system-frontend/issues/25) do Front-end e já disponibilizada em dev.

**Comment by Albertodc1981** [comment]
Bom dia mano Show!!!

Em sex., 17 de mai. de 2024 às 10:06, Bryan Santos ***@***.***>
escreveu:
